### ISSUE TITLE
Serverless log repo move

### ISSUE THREAD

**Issue by AlCutter** [sequentech/bulletin-board#78]
Hi @edulix,

I remember that you're using the serverless log code in here (which is awesome!), so I just wanted to let you know that we've "promoted" it out of google/trillian-examples and into its own repo: https://github.com/transparency-dev/serverless-log

You'll probably appreciate that the new repo [has a significantly smaller set of dependencies](https://github.com/transparency-dev/serverless-log/blob/main/go.mod) compared to `trillian-examples`.

I would've just sent you a PR updating the imports, but I'm afraid I can't due to licensing in this repo - nonetheless I wanted to get in touch and let you know about the move.

Cheers,
Al.

**Comment by edulix** [comment]
Thanks! We're currently not using it but that was great of you to tell us. We'll review it.
